FROM nginx:latest
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./dummy_data/1MB.html /usr/share/nginx/html/1MB.html
COPY ./dummy_data/10KB.html /usr/share/nginx/html/10KB.html
COPY ./dummy_data/dummy.jpg /usr/share/nginx/html/dummy.jpg
