FROM nginx:latest
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./dummy_data/1MB.html /usr/share/nginx/html/1MB.html
COPY ./dummy_data/100MB.html /usr/share/nginx/html/100MB.html
COPY ./dummy_data/10KB.html /usr/share/nginx/html/10KB.html
